In [9]:
# numpy
import numpy as np

a=np.array([[0,1],[2,3]])
b=np.array([[1,2],[3,4]])
c=[[1,2,3],[3,4,5]]
print(a,'\n',b,'\n')
# 矩阵各元素的平方
print(np.arange(1,20,5),np.arange(4)**2,np.sin(np.arange(4)))
c=np.asarray(c)
print('将列表c转为矩阵：',c)
c=c.tolist()
print('将矩阵c转为列表：',c)
print('矩阵相乘：',np.dot(a,b))
print('矩阵相加：',a+b)
print('对应元素相乘：',a*b)
print('数组a的最大值：',np.argmax(a))
print('索取数组a中的元素：',a[1][1])

a=a.flatten()
print('将a压为一维数组：',a)
# 此时a = [0 1 2 3]
print('获取数组a中的单个元素：',a[1])
print('获取数组a中的元素：',a[np.array([0, 1, 3])])
print('对数组a切片：',a[1:4])
print('取出数组b的第2列：',b[:,1])
print('获取满足一定条件的元素：',a[a>2])
print('查看数组中的数据类型：',a.dtype)
print('求数组a的和：',np.sum(a))
print('求数组a的平均值：',np.mean(a))
print('求数组a的最小值：',np.min(a))
print('数组a的最小值索引：',np.argmin(a))
print('求数组a的标准差：',a.std())

# axis=1：按行计算 axis=0：按列计算
print('按行计算：','求和', b.sum(axis=1),'平均值',b.mean(axis=1))
print('按列计算：','求和', b.sum(axis=0),'平均值',b.mean(axis=0))
a[:]=5
print('将向量的元素全部赋值为５：',a)



print('获取数组b的维数：',np.ndim(b))
print('获取数组b的形状：',b.shape)
print('获取数组b行列个数：',b.shape[0],b.shape[1])
print('生成[0,1)之间随机浮点数，形状为5*1',np.random.rand(5))
print('生成标准正态分布的随机样本数,形状为3*2：',np.random.rand(3,2))
print('生成标准正态分布的随机样本数,形状为3*2，取值范围[-1,1]：',np.random.rand(3,2)*2-1)
print('生成长度为3的向量：',np.arange(4))
print('生成长度为7的向量：',np.empty(7, dtype=int))
print('生成一个矩阵，并将矩阵的元素赋值为固定值,如7：',np.full((3, 5), 7, dtype=int))

[[0 1]
 [2 3]] 
 [[1 2]
 [3 4]] 

[0 1 2 3] [0 1 4 9] [0.         0.84147098 0.90929743 0.14112001]
将列表c转为矩阵： [[1 2 3]
 [3 4 5]]
将矩阵c转为列表： [[1, 2, 3], [3, 4, 5]]
矩阵相乘： [[ 3  4]
 [11 16]]
矩阵相加： [[1 3]
 [5 7]]
对应元素相乘： [[ 0  2]
 [ 6 12]]
数组a的最大值： 3
索取数组a中的元素： 3
将a压为一维数组： [0 1 2 3]
获取数组a中的单个元素： 1
获取数组a中的元素： [0 1 3]
对数组a切片： [1 2 3]
取出数组b的第2列： [2 4]
获取满足一定条件的元素： [3]
查看数组中的数据类型： int32
求数组a的和： 6
求数组a的平均值： 1.5
求数组a的最小值： 0
数组a的最小值索引： 0
求数组a的标准差： 1.118033988749895
按行计算： 求和 [3 7] 平均值 [1.5 3.5]
按列计算： 求和 [4 6] 平均值 [2. 3.]
将向量的元素全部赋值为５： [5 5 5 5]
获取数组b的维数： 2
获取数组b的形状： (2, 2)
获取数组b行列个数： 2 2
生成[0,1)之间随机浮点数，形状为5*1 [0.39243779 0.24203935 0.77221697 0.93279152 0.1562685 ]
生成标准正态分布的随机样本数,形状为3*2： [[0.21155152 0.94876206]
 [0.54014114 0.29501554]
 [0.24859552 0.82812075]]
生成标准正态分布的随机样本数,形状为3*2，取值范围[-1,1]： [[-0.49740432 -0.86020527]
 [-0.62703597 -0.8643569 ]
 [ 0.33522383 -0.37709185]]
生成长度为3的向量： [0 1 2 3]
生成长度为7的向量： [         0          1          0 1988382253       1028          0
        768]
生成一个矩阵，并将矩阵的

In [113]:
a

array([5, 5, 5, 5])

In [138]:
# pandas一维数据
import pandas as pd
m=pd.Series(range(7),index=['红','橙','黄','绿','青','蓝','紫'])
n=pd.Series(range(8),index=['红','橙','黄','绿','青','蓝','紫','白'])
print(m,n)
print('获取数组统计信息：',m.describe())
print('根据位置获取数组元素：',m.iloc[1])
print('根据索引获取数组元素：',m.loc['橙'])
r=m+n
print('列表相加',r) #用加号+直接相加，索引值相同的元素才会相加，只出现在一个数组里的索引相加之后的值为空值
print('删除列表空值',r.dropna())
r=m.add(n,fill_value=0)
print('用add将两个数组相加，并用fill_value指定一个数据来填充缺失值：',r)


红    0
橙    1
黄    2
绿    3
青    4
蓝    5
紫    6
dtype: int64 红    0
橙    1
黄    2
绿    3
青    4
蓝    5
紫    6
白    7
dtype: int64
获取数组统计信息： count    7.000000
mean     3.000000
std      2.160247
min      0.000000
25%      1.500000
50%      3.000000
75%      4.500000
max      6.000000
dtype: float64
根据位置获取数组元素： 1
根据索引获取数组元素： 1
列表相加 橙     2.0
白     NaN
紫    12.0
红     0.0
绿     6.0
蓝    10.0
青     8.0
黄     4.0
dtype: float64
删除空值 橙     2.0
紫    12.0
红     0.0
绿     6.0
蓝    10.0
青     8.0
黄     4.0
dtype: float64
用add将两个数组相加，并用fill_value指定一个数据来填充缺失值： 橙     2.0
白     7.0
紫    12.0
红     0.0
绿     6.0
蓝    10.0
青     8.0
黄     4.0
dtype: float64


In [38]:
# pandas二维数据
import pandas as pd
p={'购药时间':['20点49分','20点50分','20点51分'],
'商品编号':['001','002','003'],
'商品名称':['牡丹','金银花','芍药'],
'金额':[20,10,15]}
q=pd.DataFrame(p)
print(q)
# 从collections中导入有序字典OrderedDict
# from collections import OrderedDict
# p=OrderedDict(p)
# q=pd.DataFrame(p)
print('',q.mean())
# iloc根据元素的位置查询，loc根据元素的索引查询
print('根据位置查询元素',q.iloc[0,2])
print('获取某第3列',q.iloc[:,2],q.loc[:,'商品名称'],q['商品名称'])
print('根据索引查询元素',q.loc[0,'商品名称'])
print('获取多列',q.iloc[:,1:3],q[['商品编号','商品名称']])

promise=q.loc[:,'金额']>10
print('构造条件，选择金额大于10的数据',promise)
print('查询满足条件的数据',q.loc[promise,:])
print('查询数据行列数',q.shape)
print('获取数据统计信息：',q.describe())




     购药时间 商品编号 商品名称  金额
0  20点49分  001   牡丹  20
1  20点50分  002  金银花  10
2  20点51分  003   芍药  15
 商品编号    334001.0
金额          15.0
dtype: float64
根据位置查询元素 牡丹
获取某第3列 0     牡丹
1    金银花
2     芍药
Name: 商品名称, dtype: object 0     牡丹
1    金银花
2     芍药
Name: 商品名称, dtype: object 0     牡丹
1    金银花
2     芍药
Name: 商品名称, dtype: object
根据索引查询元素 牡丹
获取多列   商品编号 商品名称
0  001   牡丹
1  002  金银花
2  003   芍药   商品编号 商品名称
0  001   牡丹
1  002  金银花
2  003   芍药
构造条件，选择金额大于10的数据 0     True
1    False
2     True
Name: 金额, dtype: bool
查询满足条件的数据      购药时间 商品编号 商品名称  金额
0  20点49分  001   牡丹  20
2  20点51分  003   芍药  15
查询数据行列数 (3, 4)
获取数据统计信息：          金额
count   3.0
mean   15.0
std     5.0
min    10.0
25%    12.5
50%    15.0
75%    17.5
max    20.0


In [ ]:
# pandas处理excel文件
import pandas as pd
# 为了保证某些列的数据在读取之后保持正确，可以用dtype=’object’使导入的数据都是字符串格式，并用head()打印出前5行，查看数据导入是否正确，都有哪些数据，以便了解原数据的特点
filename='C:\\ze\\xxx.xls'
xls=pd.ExcelFile(filename,dtype='object')
data=xls.parse('Sheet1',dtype='object')
print(data.head())

# 使用columns和rename进行指定列重命名。
# 在数据框中使用columns可以返回一个列索引的列表，先用columns构建一个新旧列名对应的字典，再通过rename进行重命名。
# 这里要注意rename后面的括号里，逗号前面的格式一定要是columns=字典名或columns=具体的字典，其他形式无效；
# 默认inplace等于False，代表原数据框不变，会创建一个更改后新的数据框，inplace等于True时，表示在数据框本身进行改动。
print(data.columns)
col={'购药时间':'销售时间','商品名称':'药品名称'}
data.rename(columns=col,inplace=True)
# 通过dropna删除缺失值
# subset:list，表示在哪些列中查看缺失值，
# how='any'与省略掉的默认的axis=0配合使用，表示如何删掉缺失值：any表示只要有缺失值，就删掉对应行。
# inplace=False，表示将修改后的数据框新建一个
print(data.describe())
data2=data.dropna(subset=['销售时间','药品名称'],how='any',inplace==False)
print(data2.head())
# 数据类型转换
data2['金额']=data2['金额'].astype('float')

